# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Heart Rate Monitor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'SVProgressHUD'
  pod 'Hero'
  pod "lottie-ios"
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Charts'

  # Pods for Heart Rate Monitor

  target 'Heart Rate MonitorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Heart Rate MonitorUITests' do
    # Pods for testing
  end

end
